# name: Versioning

# on:
#   pull_request:
#     types: [opened, synchronize]

permissions: write-all
jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 14"
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: "Setup npm"
        run: |
          npm set @xcanchal:registry=https://npm.pkg.github.com/xcanchal
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.PAT_GITHUB2 }}"

      - name: Update
        run: |
          npm install

      - name: Install dependencies
        run: |
          npm ci
          npx lerna bootstrap