name: semantic release using lerna

on:
  push:
    branches:
      - master
permissions: write-all

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Run test
        run: npm run test

      - name: Update version
        run: npm run new-version

      