name: Versioning

on:
  push:
    branches:
      - master  # Modify this according to your branch name

    tags:
      - "*"
permissions: write-all
jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Modify this according to your Node.js version requirements

      - name: Install dependencies
        run: npm install 

      - name: Print Changed Files
        run: |
          git fetch --depth=1 origin ${GITHUB_REF}
          git diff --name-only HEAD FETCH_HEAD

      - name: Print Changed Files
        run: npx lerna changed --json

      # - name: Commit changes
      #   run: |
      #     git config user.name "${{ github.actor }}"
      #     git config user.email "${{ github.actor }}@users.noreply.github.com"
      #     git add package-lock.json package.json
      #     git commit -m "Committing changes before versioning"


      - name: Create Git Release
        uses: actions/github-script@v4
        with:
          script: |
            const tag = context.ref.replace('refs/tags/', '');
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            const { owner, repo } = context.repo;

            const createReleaseResponse = await octokit.rest.repos.createRelease({
              owner,
              repo,
              tag_name: tag,
              name: `Release ${tag}`,
              body: 'Enter release notes here',
              draft: false,
              prerelease: false
            });

            console.log(`Created release ${createReleaseResponse.data.name} (${createReleaseResponse.data.tag_name})`);

      # - name: Push changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     branch: ${{ github.ref }}
      #     github_token: ${{ secrets.PAT_GITHUB2 }}


# name: semantic release using lerna

# on:
#   push:
#     branches:
#       - master
# permissions: write-all

# jobs:
#   version:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Install Dependencies
#         run: npm install lerna

#       - name: Run test
#         run: npx lerna init

#       - name: Update version
#         run: npm run new-version
