name: Versioning

on:
  pull_request:
    types: [closed]
    branches:
      - master

permissions: write-all
jobs:
  versioning:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: "Use NodeJS 18"
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install

    - name: Print Changed Files
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git diff --name-only HEAD FETCH_HEAD

    - name: Commit changes
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git checkout -- package-lock.json

    - name: Print Changed Files
      run: |
        npx lerna init --independent
        npx lerna changed --json

    - name: "Version and publish" # Interesting step
      env:
        GH_TOKEN: ${{ secrets.PAT_GITHUB2 }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"
        npx lerna version --conventional-commits --yes
        npx lerna publish from-package --yes

      # - name: Commit changes
      #   run: |
      #     git config user.name "${{ github.actor }}"
      #     git config user.email "${{ github.actor }}@users.noreply.github.com"
      #     git add package-lock.json package.json
      #     git commit -m "Committing changes before versioning"

      # - name: Push changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     branch: ${{ github.ref }}
      #     github_token: ${{ secrets.PAT_GITHUB2 }}
