name: Semantic Release using Lerna

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Lerna
        run: npm install -g lerna

      # - name: Install dependencies
      #   run: npm ci --ignore-scripts

      - name: Run tests
        run: npm run test

      - name: Semantic Release
        run: |

          # Run Lerna's version command to determine the next version
          lerna version --conventional-commits --yes

          # Publish updated packages
          lerna publish from-git --yes
