# name: Versioning

# on:
#   push:
#     branches:
#       - master

# permissions: write-all

# jobs:
#   versioning:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 14

#       - name: Install dependencies
#         run: npm install lerna

#       - name: Commit changes
#         run: |
#           git config user.name "${{ github.actor }}"
#           git config user.email "${{ github.actor }}@users.noreply.github.com"
#           git add .
#           git diff --cached --quiet || git commit -m "Committing changes before versioning"


#       - name: Get changed packages
#         id: changed-packages
#         run: |
#           changed_packages=""
#           while IFS= read -r file; do
#             package=$(dirname "$file")
#             if [[ $package == packages/aws/ecs/ecs-simple/* || $package == packages/aws/eks/eks-simple/* ]]; then
#               package=${package#packages/}
#               package=${package%%/*}
#               changed_packages+="$package "
#             fi
#           done < <(git diff --name-only HEAD~1 HEAD)
#           changed_packages=$(echo "$changed_packages" | tr ' ' '\n' | sort -u)
#           echo "::set-output name=packages::$changed_packages"

#       - name: Lerna versioning
#         run: |
#           changed_packages=${{ steps.changed-packages.outputs.packages }}
#           if [[ -n $changed_packages ]]; then
#             npx lerna version --conventional-commits --yes --scope $changed_packages
#           else
#             echo "No packages changed, skipping versioning."
#           fi

#       - name: Push changes
#         uses: ad-m/github-push-action@v0.6.0
#         with:
#           branch: ${{ github.ref }}
#           github_token: ${{ secrets.PAT_GITHUB2 }}





name: Versioning

on:
  push:
    branches:
      - master  # Modify this according to your branch name
permissions: write-all
jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Modify this according to your Node.js version requirements

      - name: Install dependencies
        run: npm install 

      # - name: Commit changes
      #   run: |
      #     git config user.name "${{ github.actor }}"
      #     git config user.email "${{ github.actor }}@users.noreply.github.com"
      #     git add package-lock.json package.json
      #     git commit -m "Committing changes before versioning"


      - name: Lerna versioning
        run: |
          npx lerna version --conventional-commits --conventional-graduate --yes
          npx lerna publish from-git --yes

      # - name: Push changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     branch: ${{ github.ref }}
      #     github_token: ${{ secrets.PAT_GITHUB2 }}

      # - name: Publish packages
      #   run: npx lerna publish from-git --yes



# name: semantic release using lerna

# on:
#   push:
#     branches:
#       - master
# permissions: write-all

# jobs:
#   version:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Install Dependencies
#         run: npm install lerna

#       - name: Run test
#         run: npx lerna init

#       - name: Update version
#         run: npm run new-version
